[package]
name = "airust"
version = "0.1.1"
authors = ["LEVOGNE"]
edition = "2021"
description = "Trainierbare, modulare KI-Engine in Rust mit Compile-Zeit-Wissen"
license = "MIT"
readme = "README.md"
keywords = ["ai", "machine-learning", "knowledge", "compile-time"]
categories = ["science", "development-tools::testing"]
documentation = "https://docs.rs/airust"
homepage = "https://github.com/LEVOGNE/airust"
repository = "https://github.com/LEVOGNE/airust"
 
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.18"
strsim = "0.10"

[build-dependencies]
serde_json = "1.0"
